### PR TITLE
Remove matplotlib<3.11 compatibility pin

### LINKED ISSUE #231: Remove matplotlib<3.11 pin once arviz_plots is compatible
## Background

In #229 we added a temporary runtime pin `matplotlib<3.11` to `pyproject.toml` (and `uv.lock`).

matplotlib 3.11.0 removed `matplotlib.style.core`, which `arviz_plots` (<=1.1, pulled in transitively via `arviz`) still imports at module load time. This broke CI with:

```
AttributeError: module 'matplotlib.style' has no attribute 'core'
```

Both the **Build Docs** and **Build source and wheel distributions** jobs do a fresh `pip install` with unpinned dependencies, so they picked up the broken matplotlib. The pin keeps matplotlib at <3.11 to keep CI green.

## Action

Once `arviz_plots` ships a release that is compatible with matplotlib >=3.11 (i.e. no longer references `matplotlib.style.core` at import), remove the workaround:

- Drop the `matplotlib<3.11` entry and its explanatory comment from `dependencies` in `pyproject.toml`.
- Regenerate `uv.lock` (`uv lock`).
- Confirm a clean install + `import pathmc` works on matplotlib >=3.11 and that the docs/sdist CI jobs pass.

## Tracking

- Upstream: watch for an `arviz_plots` release that fixes the `matplotlib.style.core` usage.
- Introduced by: #229

### PR DESCRIPTION
**Pull request by drbenvincent**
Closes #231.

## Summary
- Remove the temporary `matplotlib<3.11` dependency pin.
- Refresh `uv.lock` to ArviZ/arviz-plots 1.2.0 and matplotlib 3.11.1.

## Verification
- Confirmed upstream `arviz-plots` 1.2.0 no longer references `matplotlib.style.core`.
- `make test-fast`
- `make lint`
- `make check-build`
- `make docs` (22 existing unresolved-link warnings)

### CODE REVIEW

**Comment by drbenvincent** [comment]
Block check date: 2026-08-07

I verified that issue #231 was open with the exact `blocked?` label, then checked the blocker end to end: `arviz-plots` v1.2.0 was released on 2026-06-12 without the `matplotlib.style.core` import, and ArviZ v1.2.0 now resolves that compatible plotting release. A clean locked environment resolved ArviZ 1.2.0, arviz-plots 1.2.0, and matplotlib 3.11.1; `import pathmc` passed.

Implementation removes the temporary matplotlib upper bound and refreshes `uv.lock`. I ran `make test-fast` (1209 passed), `make lint`, `make check-build` (sdist and wheel imports passed), and `make docs` (completed with 22 existing unresolved-link warnings).

**Review by drbenvincent — COMMENTED** [review]
## Review (LGTM — cannot self-approve)

Reviewed against #231 requirements:

- **pyproject.toml**: `matplotlib>=3.9,<3.11` pin and comment removed; lower bound kept at `>=3.9`.
- **uv.lock**: regenerated to ArviZ 1.2.0 (arviz-base/plots/stats) and matplotlib 3.11.1.
- **Install smoke test**: `uv sync` + import of `pathmc`, `arviz`, `arviz_plots` succeeds with matplotlib 3.11.1.
- **CI**: all checks green (prek, test, build, docs).

The incidental `pexpect`/`ptyprocess` marker tweak in the lockfile is a harmless uv regeneration artifact.

Local `make test-fast` hit an unrelated missing `pyarrow` optional dep in this worktree; CI test job passed in full.

**Verdict**: Ready to merge. (GitHub blocked self-approval on this PR.)
