### ISSUE TITLE
Remove matplotlib<3.11 pin once arviz_plots is compatible

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/pathmc#231]
## Background

In #229 we added a temporary runtime pin `matplotlib<3.11` to `pyproject.toml` (and `uv.lock`).

matplotlib 3.11.0 removed `matplotlib.style.core`, which `arviz_plots` (<=1.1, pulled in transitively via `arviz`) still imports at module load time. This broke CI with:

```
AttributeError: module 'matplotlib.style' has no attribute 'core'
```

Both the **Build Docs** and **Build source and wheel distributions** jobs do a fresh `pip install` with unpinned dependencies, so they picked up the broken matplotlib. The pin keeps matplotlib at <3.11 to keep CI green.

## Action

Once `arviz_plots` ships a release that is compatible with matplotlib >=3.11 (i.e. no longer references `matplotlib.style.core` at import), remove the workaround:

- Drop the `matplotlib<3.11` entry and its explanatory comment from `dependencies` in `pyproject.toml`.
- Regenerate `uv.lock` (`uv lock`).
- Confirm a clean install + `import pathmc` works on matplotlib >=3.11 and that the docs/sdist CI jobs pass.

## Tracking

- Upstream: watch for an `arviz_plots` release that fixes the `matplotlib.style.core` usage.
- Introduced by: #229
